---
# tasks file for Istio-role
- name: Create istio install directory
  file:
    path: "{{ istio_install_dir }}"
    state: directory

- name: Download Istio archive
  get_url:
    url: "https://github.com/istio/istio/releases/download/{{ istio_version }}/istio-{{ istio_version }}-linux-amd64.tar.gz"
    dest: "/tmp/istio-{{ istio_version }}.tar.gz"
    mode: '0644'

- name: Extract Istio archive
  unarchive:
    src: "/tmp/istio-{{ istio_version }}.tar.gz"
    dest: "{{ istio_install_dir }}"
    remote_src: yes

- name: Add istioctl to PATH
  copy:
    content: |
      export PATH=$PATH:{{ istio_install_dir }}/istio-{{ istio_version }}/bin
    dest: /etc/profile.d/istio.sh
    mode: '0755'

- name: Install Istio using istioctl
  shell: >
    {{ istio_install_dir }}/istio-{{ istio_version }}/bin/istioctl install
    --set profile={{ istio_profile }} -y
  args:
    executable: /bin/bash
  environment:
    PATH: "{{ istio_install_dir }}/istio-{{ istio_version }}/bin:{{ ansible_env.PATH }}"
